# CI/CD workflow for FastAPI project
# This workflow installs dependencies, runs tests, and can be extended for deployment.

name: CI/CD FastAPI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: List installed packages
        run: pip list

  build-image:
    permissions:
      packages: write # Grant write permission for GitHub Packages
      contents: read # Grant read permission for repository contents
    uses: kuroroluzbell/centralizado/.github/workflows/build-and-push-docker.yml@main # Asegúrate de usar la rama correcta (ej. main)
    with:
      dockerfile_path: './Dockerfile' # Ruta a tu Dockerfile en este repositorio
      image_name: 'nombre-de-tu-aplicacion' # El nombre que quieras para la imagen
      tags: 'latest,${{ github.sha }}' # Etiquetas para la imagen. Puedes añadir más si lo necesitas.
      # context: '.' # Opcional: la ruta del contexto de construcción si no es la raíz.
    #secrets:
      # registry_username: ${{ secrets.DOCKER_USERNAME }}