# CI/CD workflow for FastAPI project
# This workflow installs dependencies, runs tests, and can be extended for deployment.

name: CI/CD FastAPI

on:
  push:
    branches: [main, develop]

jobs:
  build:
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: List installed packages
        run: pip list

  #build-image:
  #  permissions:
  #    packages: write # Needed to push packages to GHCR
  #    contents: read  # Needed to read repository contents
  #  uses: kuroroluzbell/centralizado/.github/workflows/build-and-push-docker.yml@main
  #  with:
  #    image_name: ${{ github.repository }}
  #    dockerfile_path: './Dockerfile'
  #   secrets:
  #    registry_username: ${{ github.actor }}
  #    registry_password: ${{ secrets.GITHUB_TOKEN }}
  build-and-push:
    if: github.event_name == 'push'
    needs: build
    permissions:
      id-token: write # Required for authenticcating with GCP Workload Identity Federation
      contents: read  # Often required to checkout code for the build
    uses: kuroroluzbell/centralizado/.github/workflows/build-and-push-docker-gcp.yml@main
    with:
      image_name: ${{ github.repository }}
      artifact_registry_region: "us-central1" # La regi√≥n de tu repositorio de Artifact Registry
      artifact_registry_repository: "demo" # El nomdbre de tu repositorio de Artifact Registrys
    secrets:
      gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}